# Generated by Django 2.2.1 on 2019-08-31 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentResponsible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departmentResponsible_department', to='department.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentResponsible_employee', to='employee.Employee')),
            ],
            options={
                'unique_together': {('department', 'employee')},
            },
        ),
    ]
