# Generated by Django 2.2.1 on 2019-08-31 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('personal_number', models.CharField(default='', max_length=8, unique=True)),
                ('first_name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('birthday', models.DateField(blank=True, default='')),
                ('gender', models.BooleanField(blank=True, default=0)),
                ('tel_number', models.BigIntegerField(blank=True, default=0)),
                ('internal_number', models.IntegerField(blank=True, default=0)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('driver_license', models.BooleanField(blank=True, default='')),
                ('position', models.CharField(blank=True, default='', max_length=70)),
                ('title', models.CharField(blank=True, default='', max_length=70)),
                ('authorized_approver', models.BooleanField(blank=True, default=0)),
                ('address1', models.CharField(blank=True, default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=100)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_country', to='country.Country')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='department.Department')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_responsible', to='employee.Employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
