# Generated by Django 2.2.1 on 2019-08-31 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourceTeam', '0001_initial'),
        ('requesterTeam', '0001_initial'),
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(default='', max_length=12, unique=True)),
                ('date_start', models.DateField(default='')),
                ('date_end', models.DateField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requesterTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseReport_requesterTeam', to='requesterTeam.RequesterTeam')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseReport_rule', to='rule.Rule')),
                ('sourceTeam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expenseReport_sourceTeam', to='sourceTeam.SourceTeam')),
            ],
        ),
    ]
