# Generated by Django 2.2.1 on 2019-08-31 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('sourceType', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=8, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=70)),
                ('date_start', models.DateField(blank=True, default=datetime.date.today)),
                ('date_end', models.DateField(blank=True, default=datetime.date.today)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_client', to='client.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_company', to='company.Company')),
                ('sourceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_sourceType', to='sourceType.SourceType')),
            ],
        ),
    ]
